# Generated by Django 4.2.5 on 2023-10-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskTitle2", models.CharField(max_length=30)),
                ("taskDesc2", models.TextField()),
            ],
        ),
    ]
